name: Ali Alkhatib
author: Ali Alkhatib
url: https://ali-alkhatib.com
baseurl: ''
twitter: '_alialkhatib'
email: 'hi@al2.in'
fb: 'Ali.Alkhatib'

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

liquid:
  error_mode: lax

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

permalink: /blog/:title

navigation:
    - title: home
      link: /
      name: home
    - title: research
      link: /research
      name: research
    - title: blog
      link: /blog
      name: blog
    - title: contact
      link: /contact
      name: contact
    - title: CV
      link: /content/ali_alkhatib_cv.pdf
      name: CV

gems:
  - jekyll-redirect-from


collections:
  books:
    output: true
    permalink: /books/:name