name: Ali Alkhatib
author: Ali Alkhatib
url: https://ali-alkhatib.com
base: ''
twitter: '@alialkhatib_'

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: pygments

redcarpet: extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

permalink: /blog/:title

navigation:
    - title: home
      link: /
    - title: research
      link: /research
    - title: blog
      link: /blog/
    - title: contact
      link: /contact
    - title: CV
      link: /content/CV.pdf