name: Ali Alkhatib
author: Ali Alkhatib
url: https://ali-alkhatib.com
base: ''
twitter: '_alialkhatib'
email: 'ali.alkhatib@cs.stanford.edu'
fb: 'Ali.Alkhatib'

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

permalink: /blog/:title

navigation:
    - title: home
      link: /
    - title: research
      link: /research
    - title: blog
      link: /blog
    - title: contact
      link: /contact
    - title: CV
      link: /content/CV.pdf