name: Ali Alkhatib
author: Ali Alkhatib
url: https://ali-alkhatib.com
baseurl: ''
twitter: '_alialkhatib'
email: 'hi@al2.in'
fb: 'Ali.Alkhatib'
meeting: "https://calendly.com/alialkhatib/watercooler"

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

kramdown:
  input: GFM

liquid:
  error_mode: lax

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

permalink: /blog/:title

navigation:
    - title: home
      link: /
      name: homepage
    - title: research
      link: /research
      name: page summarizing some of my published research
    - title: blog
      link: /blog
      name: blog posts
    - title: contact
      link: /contact
      name: contact page
    - title: CV
      link: /content/ali_alkhatib_cv.pdf
      name: Curriculum Vitae (PDF)

plugins:
  - jekyll-redirect-from
  - jekyll-gist


collections:
  books:
    output: true
    permalink: /books/:name
