name: Ali Alkhatib
author: Ali Alkhatib
url: https://ali-alkhatib.com
baseurl: ''
twitter: '_alialkhatib'
email: 'hi@al2.in'
fb: 'Ali.Alkhatib'
meeting: "https://calendly.com/alialkhatib/watercooler"

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge


kramdown:
  input: GFM

liquid:
  error_mode: lax

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

permalink: /blog/:title

navigation:
    - title: research
      link: /research
      name: published research
    - title: blog
      link: /blog
      name: blog posts
    - title: contact
      link: /contact
      name: contact page
    - title: CV
      outbound: true
      link: /content/ali_alkhatib_cv.pdf
      name: Curriculum Vitae (PDF)


plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-gist

feed:
    posts_limit: 20



collections:
  books:
    output: true
    permalink: /books/:name
